PCF-127 rmarkdown
eastgenomics/eggd_pancan_report_generator pull request #2
Opened 2023-07-21 13:59 UTC by Aisha-D

Working rmarkdown that inputs tsvs from the command line of the app and outputs a html

2023-07-31 15:08 UTC, nadia31415 requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2)* status: all files reviewed, 4 unresolved discussions (waiting on @Aisha-D and @jsunhs)

___
*[`resources/home/dnanexus/chimeraviz.R` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagQ53D37cq9WKMFeOP:-NagQ53D37cq9WKMFeOQ:b-rqd6si) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/chimeraviz.R#L16)):*
> ```
> 
> 
> # get ensb ann
> ```

Could you clarify this comment, did you mean ensb annotations?
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagR2Vd3wanSuSc-w1w:-NagR2Vd3wanSuSc-w1x:b-iqq8ff) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L48)):*
> ```
> ## 1. Sample Info
> ```{r}
> fusion_abdriged <- read.csv("MB2002.FusionInspector.fusions.abridged.tsv.coding_effect", sep = "\t")
> ```

Is this file static or is it sample dependent? Also is this file subject to  version control? Could be inputted through an argument if it will keep changing instead of being hard coded into the script.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 128 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagSmoSDZZi5yUSh9g-:-NagSmoT-KdSblKT8ei-:bejts39) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L128)):*
> ```
> rnaseqc_coverage_hgnc <- rnaseqc_coverage[which(rnaseqc_coverage$hgnc_symbol %in% capture_genes$V1),]
> max_cov <- as.numeric(rnaseqc_coverage_hgnc[order(rnaseqc_coverage_hgnc$coverage_mean, decreasing = T),][1,"coverage_mean"])
> max_gene <-  rnaseqc_coverage_hgnc[order(rnaseqc_coverage_hgnc$coverage_mean, decreasing = T),][1,"hgnc_symbol"]                 
> ```

Is there a way to generate the plot where you can hover over the points and see the gene name? Might be useful for the scientists with any outliers
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 210 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagTewS64bNiY9PCssz:-NagTewS64bNiY9PCst-:b-tvzja8) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L210)):*
> ```
> fusion_abdriged$X.FusionName <- gsub("--", "::",fusion_abdriged$X.FusionName)
> fusion_abdriged <- fusion_abdriged[,c(1:30,34,35,31,32,33)]
> datatable(fusion_abdriged, rownames = F)
> ```

Is there a way to make the 'FUSION_CDS' column more readable, it extends the fusion as 1 long line with may be difficult to interpret if it needs inspecting 


<!-- Sent from Reviewable.io -->

2023-08-02 07:56 UTC, Aisha-D reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @jsunhs and @nadia31415)

___
*[`resources/home/dnanexus/chimeraviz.R` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagQ53D37cq9WKMFeOP:-Nam5ci7Df_Iq5sGMJ6Q:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/chimeraviz.R#L16)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Could you clarify this comment, did you mean ensb annotations?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 48 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagR2Vd3wanSuSc-w1w:-Nam6-gI9fBxZHpWa--L:b-htnkou) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L48)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Is this file static or is it sample dependent? Also is this file subject to  version control? Could be inputted through an argument if it will keep changing instead of being hard coded into the script.
</blockquote></details>

Done. It was meant to be one of the parameters args but forgot to change it during testings. Corrected now thanks! 
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 128 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagSmoSDZZi5yUSh9g-:-Nam86yq8GdyRbunOdTW:blky7f0) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L128)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Is there a way to generate the plot where you can hover over the points and see the gene name? Might be useful for the scientists with any outliers
</blockquote></details>

There is plotly but I couldn't find a way to correct the boxplot so have used the static version of the plot. I'm thinking they can figure out which genes are outliers based on the RNAseq Coverage table. Hoping to fix the bug in the next version.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 210 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagTewS64bNiY9PCssz:-Namw2Z61dMrz32LKY5Z:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L210)):*
<details><summary><i>Previously, nadia31415 wrote…</i></summary><blockquote>

Is there a way to make the 'FUSION_CDS' column more readable, it extends the fusion as 1 long line with may be difficult to interpret if it needs inspecting 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-08 00:13 UTC, jsunhs reviewed
This is just a grammar check. I need to run through the code with real data to fully check this code.

Apart from the comments added, here is a summary of suggestions:
1. Pls. control errors and warnings, e.g. use tryCatch() or other methods.
2. Pls. consider the scenario of fusions with more than two partners.
3. Pls. write code comments. 
4. Pls. name and order the code chunks.

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +```{r setup, include=FALSE}
It is a good practice to set a meaningful name for the code chunks. I also find it useful to add a numerical order for a workflow with multiple steps.

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +knitr::opts_chunk$set(echo = TRUE ,warning = FALSE, message = FALSE)
How about also set up a working directory?

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +  cosmic_fusions:
By looking through these documents, I think it will be useful to add a section "References" to list the links to where these external databases were extracted, with the exact version downloaded.

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +TP_fusions <- intersect(target_list, predicted_fusions)
What happens if TP_fusions is empty?

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +fusion_abdriged$X.FusionName <- gsub("--", "::",fusion_abdriged$X.FusionName)
This is not the latest version of the codes, right?

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +      FFPM: normalized measure of the quantity of RNA-Seq fragments supporting the fusion event as:  fusion fragments per total million RNA-Seq fragments.
3 tabs and "-" in front of each line can make this block looks neat.

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +```{r Exons table}
Exons table -> Exons_table, it is better not to leave any space in a variable.

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +ref_annot <- read.delim(params$ref_annot, sep = "\t", skip = 5, header = F)
Why not read in the header?

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +ref_annot_df <- separate(data = ref_annot_df, col = attribute, into = transcript_attributes,  sep = "; ")
Is that safe to use "sep = "; ""? What happens if there is not an exact space?

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +              "protein_id", "transcript_support_level")]
Sorry to ask, without running through the code, which columns are being removed here and why?

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +fusion_abdriged_annotation$gene_fusion2 <- genes[seq_along(genes) %% 2 == 0]
What happens if a fusion contains more than 2 partners?

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +links_fusions <- grep("https://cancer.sanger.ac.uk/cosmic/fusion/overview?", links, value = TRUE)
Please tryCatch() to handle the errors in case the link is not working.

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +    my_df[i,"gene_fusion"] <- paste(gsub("_.*","",genes_vector[1]), gsub("_.*","",genes_vector[2]), sep = "-")
How to deal here with fusions with more than two partners?

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +fusion_abdriged_annotation[is.na(fusion_abdriged_annotation)] <- ""
Pls. explain the choice of using "" here in the case of is.na().

2023-09-08 00:13 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> +```
This is not the latest/full code. Pls. share the latest/full code.
Pls. add a References section.

2023-09-18 16:52 UTC, Aisha-D reviewed
1. done.
2. never came across this scenario so will need a test case to develop my code on.
3. to-do next
4. done.

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-:-NedBufXB4JyNtY4zXua:b2sw313)* status: 0 of 4 files reviewed, 19 unresolved discussions (waiting on @jsunhs and @nadia31415)

___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 21 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319195518:-NedBeoU7nFda_EBrXfy:b-9p3qie) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L21)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

By looking through these documents, I think it will be useful to add a section "References" to list the links to where these external databases were extracted, with the exact version downloaded. 
</blockquote></details>

I can list out the inputs which usually has the versions in the filename? I dont want to to have any static references as I'll have to keep changing the code depending on the databases used.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 29 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319194188:-NedARrr3P0Q7ZclbjxQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L29)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

It is a good practice to set a meaningful name for the code chunks. I also find it useful to add a numerical order for a workflow with multiple steps. 
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 30 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319194419:-NedASNf6koENlc1OnUZ:b2ei1v3) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L30)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

How about also set up a working directory? 
</blockquote></details>

Code runs on DNAnexus app so thought to not hard code it as it runs on set directory of the script anyways. It makes it easier to run and no issues when running if working directory is not set.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 52 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319196106:-NedAkh_ARDNp0LuD3Fh:b5el27t) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L52)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

This is not the latest version of the codes, right? 
</blockquote></details>

Should be yes. The fusion inspector outputs with "--" seperator and not "::" of fusion genes. I have been correctly presenting that here, I did not make the changes in fusion inspector.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 59 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319195878:-NedB-hu9tKag3iSlZab:brfxa55) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L59)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

What happens if TP_fusions is empty? 
</blockquote></details>

handled it below now :smile: 
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 169 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319198378:-NedB4TM0ZDiFk3cJ-JQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L169)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

3 tabs and "-" in front of each line can make this block looks neat. 
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 205 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319199111:-NedB7wAEpwIJrmpgGfj:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L205)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

Exons table -> Exons_table, it is better not to leave any space in a variable.
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 210 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319200782:-NedBG043vvdenIHH9o0:b-wz18wd) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L210)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

Why not read in the header?
</blockquote></details>

gtf doesnt have header. I need to manually set it below
___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 327 at r3](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#gh-1319206617:-NedBPzkDvPKr2NOipGi:bj2x3hp) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/289d9d378dc52d9a73750f2bb02193808d7c48b7/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L327)):*
<details><summary><i>Previously, jsunhs wrote…</i></summary><blockquote>

Please tryCatch() to handle the errors in case the link is not working.
</blockquote></details>

i create the URL link but never check it works. If it doesnt work, the user will be linked to a blank page.


<!-- Sent from Reviewable.io -->

2023-09-27 19:46 UTC, Aisha-D reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2)* status: 0 of 4 files reviewed, 19 unresolved discussions (waiting on @jsunhs and @nadia31415)

___
*[`resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd` line 128 at r1](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-NagSmoSDZZi5yUSh9g-:-NfNACHI88CFgD22Htmh:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_pancan_report_generator/blob/30ba56b5912c985b4455cbe80563480609fb800c/resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd#L128)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

There is plotly but I couldn't find a way to correct the boxplot so have used the static version of the plot. I'm thinking they can figure out which genes are outliers based on the RNAseq Coverage table. Hoping to fix the bug in the next version.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-10-06 03:21 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> -fusion_abdriged_annotation$gene_fusion2 <- genes[seq_along(genes) %% 2 == 0]
Is using mod the best way to separate the two partners? Once one element of an array is wrong, all the rest of the elements will be wrong. How about using a data.frame/matrix where the a pair of partner genes can be clearly located?

2023-10-06 03:24 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> -links_fusions <- grep("https://cancer.sanger.ac.uk/cosmic/fusion/overview?", links, value = TRUE)
Pls. set the link as a variable which can be modified outside the code chunk.

2023-10-06 03:32 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> -links_fusions <- grep("https://cancer.sanger.ac.uk/cosmic/fusion/overview?", links, value = TRUE)
Pls. set the link as a variable which can be modified outside the code chunk.

2023-10-06 03:35 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> -fusion_abdriged_annotation$gene_fusion_cosmic <- ""
What is "" here?

2023-10-06 03:36 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> -fusion_abdriged_annotation$gene_fusion2_CT <- c(paste("https://clinicaltrials.gov/search?term=", fusion_abdriged_annotation$gene_fusion2, "%20Fusion" , sep = ""))
Pls. set all the links as a variable which can be modified outside the code chunks.

2023-10-06 03:38 UTC, jsunhs commented on resources/home/dnanexus/Pan_Cancer_Sample_Report.Rmd
> -```{r}
This block is not finished with ```? Can this .Rmd be compiled in its current format?

2023-10-06 03:43 UTC, jsunhs reviewed
Please:
1. change the links from text to be variables which can be set and modified outside the code chunks. 
2. list the testings you have done so far. 
3. add code comments.
Thanks.

2023-11-10 14:34 UTC, jsunhs reviewed
> Reviewed 1 of 2 files at r3, 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2)* status: all files reviewed, 25 unresolved discussions (waiting on @Aisha-D and @nadia31415)



<!-- Sent from Reviewable.io -->

2023-11-10 14:34 UTC, jsunhs approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2#-:-Nite1227N2TiPwRk8JU:bnfp4nl)* status: all files reviewed, 25 unresolved discussions (waiting on @Aisha-D and @nadia31415)



<!-- Sent from Reviewable.io -->

2023-11-13 07:26 UTC, nadia31415 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2)* status: all files reviewed, 12 unresolved discussions (waiting on @Aisha-D)



<!-- Sent from Reviewable.io -->

2023-11-14 11:46 UTC, jsunhs approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pancan_report_generator/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)



<!-- Sent from Reviewable.io -->

2023-11-14 11:46 UTC, merged